# Generated by Django 4.2 on 2023-05-30 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BillingRecord',
        ),
    ]
