# Generated by Django 4.2 on 2023-05-30 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_invoice'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BillingRecord',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='Item',
        ),
    ]
